### ISSUE TITLE
Competing with community project?

### ISSUE THREAD

**Issue by Im5tu** [microsoft/NugetNinja#15]
This project popped up on my twitter feed this morning and after reading the readme, this appears to be doing the same thing as a well-known community project called [Snitch](https://github.com/spectresystems/snitch). 

Would it be possible to clarify how this is intended to differ from the community project and confirm whether or not Patrik was consulted prior to development? 

I ask the latter because at least on the surface this appears to be directly competing with a community project and i'm sure we don't want all the .NET drama like we've had
before when Microsoft copied/competed against community projects.

My intention here is not to start the aforementioned drama but rather seek clarification and intent :)

**Comment by Anduin2017** [comment]
Hi. When I start this project, it was focusing on trying to find a possible version graph as high as possible. I didn't realize that there already exists a community project called Snitch actually. I'm glad that you contacted.

This project NugetNinja is still drafting as an idea and not released any production solution. We are still arguing on this for the real problem we wanna solve.

And I totally agree with the idea that the same issue should not be solved twice or having a competing between community projects. I will try to contact the maintainers of Snitch soon.

Thanks for letting us know!

**Comment by Anduin2017** [comment]
Just sent an email to @patriksvensson . Attached below

```
Hi, Patrik Svensson,

This is Anduin at Microsoft!

Recently we are trying to brainstorm some ideas as hacking projects. And we are trying to solve some package version conflicts and upgrade suggestions. So we started a repository here:

https://github.com/microsoft/NugetNinja

However, when I was working on that, an issue suggest that this project might be competing with a community project: Snitch.

This project NugetNinja is still drafting as an idea and not released any production solution. We are still arguing on this for the real problem we wanna solve.

I can guarantee that all code and structure we are still working on our own and will not reuse or copy existing solutions or directly declare it as Microsoft's. And I totally agree with the idea that the same issue should not be solved twice or having a competing between community projects.

So I draft this email for asking some opinions or ideas about how we can build our community better. I also need to know if you think this repository is offensive to the Snitch community.

Thank you!

Anduin
```

**Comment by Im5tu** [comment]
Thanks for the honest reply and transparency, I suspected that might be the case hence the enquiry - will watch with interest :)

**Comment by isaacabraham** [comment]
There is also the well known project [Paket](https://fsprojects.github.io/Paket/]) which manages NuGet packages on the client and indeed has a default resolution strategy of max for dependencies (including transients). It might be worth looking at how that project manages and resolves the graph as well as the max strategy has several implications regarding performance compared to a min-strategy.

**Comment by Anduin2017** [comment]
I just checked Paket. Seems that's a new area that defines new dependency tree grammar with `paket.depenendencies` and `paket.lock` files. Have to say that's pretty difference with the solution that I'm proposing.

By the way, NugetNinja is still drafting and only 2 engineers are working on that. It was not built or released as a production product yet. Instead it was our hackthon project while we prefer opensource. I will mention that in the `Readme.md`.

And I will also have a sync with Paket team soon. Thanks for letting us know!

**Comment by patriksvensson** [comment]
@Im5tu @Anduin2017 Hello!

I haven't tried NugetNinja out, but it looks like a cool project from the first look!

I appreciate @Im5tu looking out for the community, but I see no problem with multiple projects solving the same thing, whether by another person like me or a company like Microsoft. From what I can see, we also use two different approaches to solve the problem.

Good luck with this project! 👍

**Comment by Anduin2017** [comment]
Thank you @patriksvensson ! Thanks for your support!

We will keep working on this project. And our primary goal now is to build an automatically upgrade suggestion. And for any further possible offensive content, feel free to let me know! I'll try my best to avoid!

**Comment by Im5tu** [comment]
Seems to all be good here then, considering this closed :) Thanks all!
