### ISSUE TITLE
NugetNinja should be opt in (!) - don't spam repos 😞 

### ISSUE THREAD

**Issue by augustoproiete** [microsoft/NugetNinja#59]
I'm sure your intentions are good, but please stop spamming repos with pull-requests, and create a process for maintainers to opt in to NugetNinja's pull-requests.

Most serious open-source projects have **contributing guidelines**, and the NugetNinja bot simply ignores the contribution guidelines set by the project maintainers.

**Comment by NugetNinja** [comment]
Good idea. I made it manual to opt in my pull requests!.

**Comment by Anduin2017** [comment]
Is opt in now.
